# 使用Numpy让你的Python科学计算更高效

- 为什么要用Numpy数组结构而不是Python本身的列表list ?

这是因为列表list的元素在系统内存中是分散存储的,而Numpy数组存储在一个均匀连续的内存块中.这样数组计算遍历所有的元素,不像list还需要对内存地址进行查找,从而节省了计算资源.

- 避免采用隐式拷贝,而是采用就地操作的方式

如写成 x\*=2 ,而非 y =x\* 2

- Numpy中有两个重要的对象

ndarray (N-dimensional array object) : 解决多维数组问题

nufunc(universal function object) : 解决对数组进行处理

# 定义数组

## 创建数组

In [8]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b[1, 1] = 10
print(a.shape)
print(b.shape)
print(a.dtype)
print(b)

(3,)
(3, 3)
int32
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


## 结构数组

In [5]:
import numpy as np
# 自定义数据类型
persontype = np.dtype({
    'names': ['name', 'age', 'chinese', 'math', 'english'],
    'formats': ['S32', 'i', 'i', 'i', 'f']
})
peoples = np.array([("ZhangFei", 32, 75, 100, 90), ("GuaYu", 24, 85, 96, 88.5),
                    ("Zhaoyu", 28, 85, 92, 96.5),
                    ("HuangZhong", 32, 65, 85, 100)],
                   dtype=persontype)
ages = peoples[:]['age']
chineses = peoples[:]['chinese']
maths = peoples[:]['math']
englishs = peoples[:]['english']
print(np.mean(ages))
print(np.mean(chineses))
print(np.mean(maths))
print(np.mean(englishs))

29.0
77.5
93.25
93.75


# Numpy运算

## 连续数组的创建

In [20]:
# 使用arange方法创建
x1 = np.arange(1, 11, 2)
# 使用linspace方法创建
x2 = np.linspace(1, 9, 5)
print(x1)
print(x2)

[1 3 5 7 9]
[ 1.  3.  5.  7.  9.]


## 算数运算

In [11]:
# 加
print(np.add(x1,x2))
# 减
print(np.subtract(x1,x2))
# 乘
print(np.multiply(x1,x2))
# 除
print(np.divide(x1,x2))
# 求N次方
print(np.power(x1,x2))
# 取余
print(np.mod(x1,x2))

[  2.   6.  10.  14.  18.]
[ 0.  0.  0.  0.  0.]
[  1.   9.  25.  49.  81.]
[ 1.  1.  1.  1.  1.]
[  1.00000000e+00   2.70000000e+01   3.12500000e+03   8.23543000e+05
   3.87420489e+08]
[ 0.  0.  0.  0.  0.]


## 统计函数

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 求数组全部元素中的最小值
print(np.amin(arr))

# 求沿axis=0轴的最小值
print(np.amin(arr, 0))

# 求沿axis=1轴的最小值
print(np.amin(arr, 1))

# 求数组全部元素中的最大值
print(np.amax(arr))

# 求沿axis=0轴的最大值
print(np.amax(arr, 0))

# 求沿axis=1轴的最大值
print(np.amax(arr, 1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


In [19]:
# 统计数组全部元素中最大值与最小值之差ptp()
print(np.ptp(arr))

# 统计沿axis=0轴中最大与最小之差
print(np.ptp(arr, 0))

# 统计沿axis=1轴最大与最小之差
print(np.ptp(arr, 1))

8
[6 6 6]
[2 2 2]


In [29]:
# 用方法percentile()可以统计数组的百分位数,代表着第p个百分位数,p的取值范围是0-100.
# p=0就是求最小值,p=50就是求均值,P=100就是求最大值;同样可以在不同轴上的百分位数
print(np.percentile(a, 50))
print(np.percentile(a, 50, axis=0))
print(np.percentile(a, 50, axis=1))

5.0
[ 4.  5.  6.]
[ 2.  5.  8.]


In [37]:
# 求中位数
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

# 求平均数
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

# 求加权平均值
arr = np.array([1, 2, 3, 4])
print(np.average(arr))
# 设定权重
wts = np.array([1, 2, 3, 4])
print(np.average(arr,weights=wts))

5.0
[ 4.  5.  6.]
[ 2.  5.  8.]
5.0
[ 4.  5.  6.]
[ 2.  5.  8.]
2.5
3.0


In [38]:
arr = np.array([1, 2, 3, 4])

# 求标准差
print(np.std(arr))
# 求方差
print(np.var(arr))

1.11803398875
1.25


# Numpy排序

在Numpy中可以使用sort函数实现对数组的排序,函数sort的具体写法是

sort(a, axis , kind , order)

默认情况下使用快速排序,在kind里,可以指定quicksort,mergesort,和heapsort分别表示快速排序,合并排序,堆排序;

同样axis默认是-1,即沿着数组的最后一个轴进行排序,可以取不同的轴或者令axis=None代表采用扁平化的方式作为一个向量进行排序;

order字段,对于结构化的数组可以指定按照某个字段进行排序

In [42]:
arr = np.array([[4, 3, 2], [2, 4, 1]])
print(np.sort(arr))
print(np.sort(arr, axis=None))
print(np.sort(arr, axis=0))
print(np.sort(arr, axis=1))

[[2 3 4]
 [1 2 4]]
[1 2 2 3 4 4]
[[2 3 1]
 [4 4 2]]
[[2 3 4]
 [1 2 4]]


# 课后作业

In [57]:
# !/usr/bin/python
# -*-coding:utf-8-*-

print("\n 本章作业\n")

import numpy as np

pensontype = np.dtype({
    'names': ['name', 'chinese', 'english', 'math'],
    'formats': ['S32', 'i', 'i', 'i']
})
peoples = np.array([('Zhangfei', 66, 65, 30), ('Guanyu', 95, 85, 98),
                    ('Zhaoyun', 93, 92, 96), ('Huangzhou', 90, 88, 70)],
                   dtype=pensontype)

# 指定的竖列
name = peoples[:]['name']
chinses = peoples[:]['chinese']
english = peoples[:]['english']
math = peoples[:]['math']


# 定义函数用于显示每一排的内容
def show(name, cj):
    print('{}|{}|{}|{}|{}|{}'.format(name, np.mean(cj), np.min(cj), np.max(cj),
                                     np.var(cj), np.std(cj)))


print("科目|平均成绩|最小成绩|最大成绩|方差|标准差")
show('语文', chinese)
show('英语', english)
show('数学', math)

print("排名")
# 用sorted函数进行排序
ranking = sorted(peoples, key=lambda x:x[1]+x[2]+x[3], reverse=True)
print(ranking)


 本章作业

科目|平均成绩|最小成绩|最大成绩|方差|标准差
语文|84.8|66|95|114.96000000000001|10.721940122944169
英语|82.5|65|92|108.25|10.404326023342406
数学|73.5|30|98|752.75|27.436289836637897
排名
[(b'Zhaoyun', 93, 92, 96), (b'Guanyu', 95, 85, 98), (b'Huangzhou', 90, 88, 70), (b'Zhangfei', 66, 65, 30)]


# 本章导图

![mapping](./img/Numpy库.png)