由于NumPy提供了一个非常易用的C语言API，这使得，将数据传递给用底层语言编写的外部类库，再由外部类库将计算结果按照NumPy数组的方式返回，变得非常简单。这个特征使得Python可以对存量C/C++/Fortran代码库进行封装，并为这些代码提供动态、易用的接口。因此是目前Python数值计算中最为重要的基础包。大多数计算包都提供了基于NumPy的科学函数功能，将NumPy的数组对象作为数据交换的通用语。Numpy之所以如此重要,主要基于以下原因:  

1.Numpy的设计对于含有大量数组的数据非常有效.  
2.NumPy在内部将数据存储在连续的内存块上，这与其他的Python内建数据结构是不同的。NumPy的算法库是用C语言写的，所以在操作数据内存时，不需要任何类型检查或者其他管理操作。NumPy数组使用的内存量也小于其他Python内建序列。  
3.NumPy可以针对全量数组进行复杂计算而不需要写Python循环。

## 测试Numpy的效率

In [1]:
import numpy as np

In [2]:
my_arr=np.arange(1000000)
my_list=list(range(100000))

In [6]:
%time for _ in range(10):my_arr2=my_arr*2

Wall time: 64 ms


In [9]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 120 ms


## 创建ndarray

NumPy的核心特征之一就是N-维数组对象——ndarray。ndarray是Python中一个快速、灵活的大型数据集容器。数组允许你使用类似于标量的操作语法在整块数据上进行数学计算。一个ndarray是一个通用的多维同类数据容器，也就是说，它包含的每一个元素均为相同类型。每一个数组都有一个shape属性，用来表征数组每一维度的数量；每一个数组都有一个dtype属性，用来描述数组的数据类型.

In [10]:
data=np.random.randn(2,3)
data

array([[-0.15775892, -0.4941898 ,  0.12200374],
       [ 0.03801489, -0.88685399, -1.30781335]])

In [11]:
data*10

array([[ -1.57758919,  -4.94189797,   1.22003741],
       [  0.38014892,  -8.8685399 , -13.07813353]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

In [14]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 4)

In [19]:
# 除非显式地指定，否则np.array会自动推断生成数组的数据类型。数据类型被存储在一个特殊的元数据dtype中。
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
data3=np.arange(15) 

由于NumPy专注于数值计算，如果没有特别指明的话，默认的数据类型是float64（浮点型）。

## ndarray的数据类型

数据类型，即dytpe，是一个特殊的对象，它包含了ndarray需要为某一种类型数据所申明的内存块信息（也称为元数据，即表示数据的数据）.

In [29]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

In [32]:
# 使用astype方法可显式地转换数组的数据类型
float_arr=arr2.astype(np.float64)
float_arr.dtype

dtype('float64')

In [35]:
# 把浮点数转换成整数，则小数点后的部分将被消除
arr=np.array([3.7,-1.2,-2.6])
arr

array([ 3.7, -1.2, -2.6])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2])

In [38]:
# 如果里面的元素都是表达数字含义的字符串，也可以通过astype将字符串转换为数字
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

在NumPy中，当使用numpy.string_类型作字符串数据要小心，因为NumPy会修正它的大小或删除输入且不发出警告。pandas在处理非数值数据时有更直观的开箱型操作。

## Numpy数组算数

In [43]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [45]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [47]:
arr*0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [48]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [49]:
arr2>arr1

array([[False,  True, False],
       [ True, False,  True]])

## 基础索引和切片

In [51]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr[5]

5

In [53]:
arr[5:8]

array([5, 6, 7])

In [55]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [56]:
# 区别于Python的内建列表，数组的切片是原数组的视图。这意味着数据并不是被复制了，任何对于视图的修改都会反映到原数组上。
arr_slice=arr[5:8]
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [57]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [58]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [60]:
arr2d[0][2]

3

In [61]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
# 可以进行多组切片,与多组索引类似
# 选择arr2d的前两“行”
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [64]:
# 选择第二行但是只选择前两列
arr2d[1,:2]

array([4, 5])

In [65]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [66]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 数组转置和换轴

In [67]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [70]:
# 计算矩阵内积
arr = np.random.randn(6, 3)
arr

array([[-0.64243777,  0.55734818, -1.55372925],
       [-0.57584476,  1.36570322,  0.89231899],
       [ 0.66387822, -1.01326484,  0.61692306],
       [ 0.73713081, -0.292935  ,  0.06129115],
       [ 0.86385668, -0.3786043 ,  0.71442409],
       [-1.72827902,  0.90515024,  0.45679842]])

In [72]:
np.dot(arr.T,arr)

array([[ 5.46161632, -3.92452247,  0.7667634 ],
       [-3.92452247,  4.25093702, -0.14739887],
       [ 0.7667634 , -0.14739887,  4.31372501]])

In [73]:
# 对于更高维度的数组，transpose方法可以接收包含轴编号的元组，用于置换轴
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [75]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

在这里，轴已经被重新排序，使得原先的第二个轴变为第一个，原先的第一个轴变成了第二个，最后一个轴并没有改变。

## 数学和统计方法

In [77]:
arr=np.random.randn(5,4)
arr

array([[ 0.51131414, -0.56843349, -1.71040294,  0.1460348 ],
       [-0.63265179, -0.10899327,  0.16209812, -0.54311332],
       [ 0.13761971,  0.41961391, -0.60908616, -0.40823395],
       [-1.32712036, -0.53312787,  0.14189995, -0.1753374 ],
       [ 0.26006368,  0.61588099,  0.59419927, -0.25485454]])

In [78]:
arr.mean()

-0.19413152696717428

In [79]:
np.mean(arr)

-0.19413152696717428

In [80]:
arr.sum()

-3.8826305393434857

In [81]:
arr.mean(axis=1)

array([-0.40537187, -0.28066507, -0.11502162, -0.47342142,  0.30382235])

In [82]:
arr.sum(axis=0)

array([-1.05077462, -0.17505973, -1.42129177, -1.23550441])

## 排序

In [83]:
arr=np.random.rand(6)
arr

array([0.88567449, 0.55410472, 0.0386764 , 0.07175002, 0.25319484,
       0.74093641])

In [85]:
arr.sort()
arr

array([0.0386764 , 0.07175002, 0.25319484, 0.55410472, 0.74093641,
       0.88567449])

In [86]:
arr=np.random.randn(5,3)
arr

array([[ 1.55748922,  0.11712944, -0.26903263],
       [-1.47811952, -0.34241568, -0.49030893],
       [-0.46357628,  0.49532475, -0.32173598],
       [ 2.88958949,  0.85972155, -0.56152623],
       [-1.41520471,  0.00779745, -0.54389176]])

In [88]:
arr.sort(1)
arr

array([[-0.26903263,  0.11712944,  1.55748922],
       [-1.47811952, -0.49030893, -0.34241568],
       [-0.46357628, -0.32173598,  0.49532475],
       [-0.56152623,  0.85972155,  2.88958949],
       [-1.41520471, -0.54389176,  0.00779745]])

## 线性代数

In [90]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [91]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [92]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [93]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [94]:
np.dot(x,np.ones(3))

array([ 6., 15.])