# Numpy是Python中专门处理高维数组的计算包

In [ ]:
Numpy 是 Python 专门处理高维数组 (high dimensional array) 的计算的包，每次使用它遇到问题都会它的官网 (www.numpy.org). 去找答案。

In [4]:
import numpy as np
my_arry = np.arange(1000000)
my_list = list(range(1000000))
print("Numpy:")
%time for _ in range(10) :my_arry2=my_arry*2
print("List:")
%time for _ in range(10):my_list2=[x*2 for x in my_list]    

Numpy:
Wall time: 44 ms
List:
Wall time: 1.51 s


In [17]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [18]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

# 创建数组

## 按部就班法

给了列表和元组原材料,用np.array()包装下即可

In [19]:
l=[3.5,5,2,8,4.2]
np.array(l)

array([3.5, 5. , 2. , 8. , 4.2])

In [20]:
t=[3.5,5,2.,8.,4.2]
np.array(t)

array([3.5, 5. , 2. , 8. , 4.2])

## 定隔定点法

- 定隔的arange:固定元素带下间隔


参数依次为起点,终点,间隔;间隔默认为1

In [21]:
print(np.arange(8))
print(np.arange(2,8))
print(np.arange(2,8,2))

[0 1 2 3 4 5 6 7]
[2 3 4 5 6 7]
[2 4 6]


注:用函数print打印numpy数组就没有arrar()的字样了,只用其内容,而且元素之间的逗号也没有了

- 定点的linspace:固定元素个数

参数依次为起点,终点,点数;点数默认为50

In [24]:
print(np.linspace(2,6,3))
print(np.linspace(3,8,11))

[2. 4. 6.]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8. ]


## 一步登天法

In [26]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [29]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
print(np.random.random((2,3,4)))

[[[0.84825685 0.45550613 0.11376493 0.00690201]
  [0.50812154 0.00422161 0.97363326 0.77431712]
  [0.5345763  0.42039751 0.87074236 0.49044429]]

 [[0.49676412 0.91359246 0.71768746 0.00284036]
  [0.67845879 0.35757291 0.14839064 0.65117663]
  [0.3508342  0.08930718 0.20696361 0.01327465]]]


In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

# 数组性质

In [35]:
arr = np.array([3.5,5,2,8,4.2])
arr

array([3.5, 5. , 2. , 8. , 4.2])

In [36]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [38]:
print( 'The type is', type(arr) )
print( 'The dimension is', arr.ndim )
print( 'The length of array is', len(arr) )
print( 'The number of elements is', arr.size )
print( 'The shape of array is', arr.shape )
print( 'The stride of array is', arr.strides )
print( 'The type of elements is', arr.dtype )

The type is <class 'numpy.ndarray'>
The dimension is 1
The length of array is 5
The number of elements is 5
The shape of array is (5,)
The stride of array is (8,)
The type of elements is float64


In [41]:
l2=[[1,2,3],[4,5,6]]
arr2d=np.array(l2)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:

print( 'The type is', type(arr2d) )
print( 'The dimension is', arr2d.ndim )
print( 'The length of array is', len(arr2d) )
print( 'The number of elements is', arr2d.size )
print( 'The shape of array is', arr2d.shape )
print( 'The stride of array is', arr2d.strides )
print( 'The type of elements is', arr2d.dtype )

The type is <class 'numpy.ndarray'>
The dimension is 2
The length of array is 2
The number of elements is 6
The shape of array is (2, 3)
The stride of array is (12, 4)
The type of elements is int32


In [45]:
arr4d=np.random.random((2,2,2,3))
arr4d

array([[[[0.0312308 , 0.19176775, 0.64484641],
         [0.81372683, 0.70032555, 0.73871111]],

        [[0.44544056, 0.58443923, 0.19391885],
         [0.36128883, 0.52202444, 0.68306499]]],


       [[[0.14426546, 0.48686838, 0.73093197],
         [0.62406886, 0.81505306, 0.99727202]],

        [[0.2509592 , 0.80212558, 0.00994248],
         [0.98074301, 0.93462757, 0.1164846 ]]]])

In [46]:
print( 'The type is', type(arr4d) )
print( 'The dimension is', arr4d.ndim )
print( 'The length of array is', len(arr4d) )
print( 'The number of elements is', arr4d.size )
print( 'The shape of array is', arr4d.shape )
print( 'The stride of array is', arr4d.strides )
print( 'The type of elements is', arr4d.dtype )

The type is <class 'numpy.ndarray'>
The dimension is 4
The length of array is 2
The number of elements is 24
The shape of array is (2, 2, 2, 3)
The stride of array is (96, 48, 24, 8)
The type of elements is float64


# 数组的存载

## numpy自身的.npy格式

用np.save函数将numpy数组保存为.npy格式

保存写法:  np.save("文件名",数组)

上载写法: np.load("文件名")


In [50]:
arr_disk=np.arange(8)
np.save("arr_disk",arr_disk)
arr_disk

array([0, 1, 2, 3, 4, 5, 6, 7])

In [51]:
np.load("arr_disk.npy")

array([0, 1, 2, 3, 4, 5, 6, 7])

## 文本.txt格式

用np.savetxt函数将numpy数组保存为.txt格式 

保存写法: np.savetxt("文件名",数组) 

上载写法: np.loadtxt("文件名")

In [56]:
arr_text=np.array([[1.,2.,3.],[4.,5.,6.]])
np.savetxt("arr_from_text.txt",arr_text)
arr_text

array([[1., 2., 3.],
       [4., 5., 6.]])

In [59]:
np.loadtxt("arr_from_text.txt")

array([[1., 2., 3.],
       [4., 5., 6.]])

## 文本.csv格式

用np.savetxt函数将numpy数组保存为.csv格式

保存写法:np.savetxt("文件名",数组,分隔符)

上载写法:np.genfromtxt("文件名",分隔符)

In [62]:
arr_from_csv=np.array([[1,2,3],[4,5,6]])
np.savetxt("arr_from_csv.csv",arr_from_csv,delimiter=';')
arr_from_csv

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.genfromtxt("arr_from_csv.csv")

array([nan, nan])

In [64]:
np.genfromtxt("arr_from_csv.csv",delimiter=";")

array([[1., 2., 3.],
       [4., 5., 6.]])

# 数组的获取

- 正规索引

- 布尔索引

- 花式索引

虽然切片操作可以由多次索引操作替代,但两者最大的区别在于:

- 切片得到的是原数组的一个视图,修改切片中的内容会改变原数组

- 索引得到的是原数组的一个复制,修改索引中的内容不会改变原数组

正规索引

In [65]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr[6]

6

In [67]:
a=arr[6]
a=1000
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[5:8]

array([5, 6, 7])

In [69]:
b=arr[5:8]
b[1]=12
arr

array([ 0,  1,  2,  3,  4,  5, 12,  7,  8,  9])

In [71]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2d[2]

array([7, 8, 9])

In [73]:
arr2d[0][2]

3

In [74]:
arr2d[0,2]

3

In [75]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
arr2d[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [77]:
arr2d[1,:2]

array([4, 5])

In [78]:
arr2d[:2,2]

array([3, 6])

布尔索引

花式索引

In [80]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [81]:
arr[[4,3,6]]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [24, 25, 26, 27]])

In [82]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [83]:
arr[:,[0,3,1,2]]

array([[ 0,  3,  1,  2],
       [ 4,  7,  5,  6],
       [ 8, 11,  9, 10],
       [12, 15, 13, 14],
       [16, 19, 17, 18],
       [20, 23, 21, 22],
       [24, 27, 25, 26],
       [28, 31, 29, 30]])

# 数组的变形

数组层面的操作有四种,分别有:
- 重塑(reshape)和打平(ravel,flatten)
- 合并(concatenate,stack)和分裂(split)
- 重复(repate)和拼接(tile)
- 其他操作(sort,insert,delete,copy)

## 重塑和打平

重塑是从低维到高维,打平是从高维到低维.

### 重塑

In [14]:
import numpy as np
arr=np.arange(12)
print(arr)
print(arr.reshape((4,3)))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


当你重塑高维矩阵时，不想花时间算某一维度的元素个数时，可以用「-1」取代，程序会自动帮你计算出来。比如把 12 个元素重塑成 (2, 6)，你可以写成 (2,-1) 或者 (-1, 6)。

In [15]:
print(arr.reshape(2,-1))
print(arr.reshape(-1,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### 打平

In [19]:
arr=np.arange(12).reshape((4,3))
print(arr)

ravel_arr=arr.ravel()
print(ravel_arr)

flatten_arr=arr.flatten()
print(flatten_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


- 行主序和列主序

行主序 (row-major order) 指每行的元素在内存块中彼此相邻，而列主序 (column-major order) 指每列的元素在内存块中彼此相邻。



在众多计算机语言中，



- 默认行主序的有 C 语言( order=‘C’ 等价于行主序)

- 默认列主序的有 Fortran 语言( order=‘F’ 等价于列主序)

在 numpy 数组中，默认的是行主序，即 order ='C'。现在可以回答本节那两个问题了。



如果你真的想在「重塑」和「打平」时用列主序，只用把 order 设为 'F'，以重塑举例：

In [22]:
print( arr.reshape((4,3), order='F') )

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


*知识点*

函数 ravel() 或 flatten() 的不同之处是

ravel() 按「行主序」打平时没有复制原数组，按「列主序」在打平时复制了原数组

flatten() 在打平时复制了原数组


用代码验证一下，首先看 flatten()，将打平后的数组 flatten 第一个元素更新为 10000，并没有对原数组 arr 产生任何影响 (证明 flatten() 是复制了原数组)

In [24]:
arr = np.arange(6).reshape(2,3)
print( arr )
flatten = arr.flatten()
print( flatten )
flatten_arr[0] = 10000
print( arr )

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


再看 ravel() 在「列主序」打平，将打平后的数组 ravel_F 第一个元素更新为 10000，并没有对原数组 arr 产生任何影响 (证明 ravel(order='F') 是复制了原数组)

In [25]:
ravel_F = arr.ravel( order='F' )
ravel_F[0] = 10000
print( ravel_F )
print( arr )

[10000     3     1     4     2     5]
[[0 1 2]
 [3 4 5]]


最后看 ravel() 在「行主序」打平，将打平后的数组 ravel_C 第一个元素更新为 10000，原数组 arr[0][0] 也变成了 10000 (证明 ravel() 没有复制原数组)

In [26]:
ravel_C = arr.ravel()
ravel_C[0] = 10000
print( ravel_C )
print( arr )

[10000     1     2     3     4     5]
[[10000     1     2]
 [    3     4     5]]


## 合并和分裂

### 合并

Numpy中实现数组合并有三种方式:
- 通州的方式concatenate
- 专门的vstack,hstack,dstack
- 极简的r_,c_

In [30]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])

In [33]:
print(np.concatenate([arr1,arr2],axis=0))
print(np.concatenate([arr1,arr2],axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


通用的东西是好，但是可能效率不高，NumPy 里还有专门合并的函数



- vstack：v 代表 vertical，竖直合并，等价于 concatenate(axis=0)

- hstack：h 代表 horizontal，水平合并，等价于 concatenate(axis=1)

- dstack：d 代表 depth-wise，按深度合并，深度有点像彩色照片的 RGB 通道

In [34]:
print( np.vstack((arr1, arr2)) )
print( np.hstack((arr1, arr2)) )
print( np.dstack((arr1, arr2)) )

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


此外，还有一种更简单的在竖直和水平方向合并的函数，r_() 和 c_()。

In [35]:
print(np.r_[arr1,arr2])
print(np.c_[arr1,arr2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


*知识点*

r_() 和 c_() 还可以实现如下功能:

1. 参数可以切片

2. 第一个参数可以是控制参数，如果它用 'r' 或 'c' 字符可生成线性代数最常用的 matrix (和二维 numpy array 稍微有些不同)

3. 第一个参数可以是控制参数，如果它写成 ‘a,b,c’ 的形式，其中

   a：代表轴，按「轴 a」来合并

   b：合并后数组维度至少是 b

   c：在第 c 维上做维度提升


In [36]:
print( np.r_[-2:2:1, [0]*3, 5, 6] )

[-2 -1  0  1  0  0  0  5  6]


In [37]:
np.r_['r', [1,2,3], [4,5,6]]

matrix([[1, 2, 3, 4, 5, 6]])

In [38]:
print( np.r_['0,2,0', [1,2,3], [4,5,6]] )
print( np.r_['0,2,1', [1,2,3], [4,5,6]] )
print( np.r_['1,2,0', [1,2,3], [4,5,6]] )
print( np.r_['1,2,1', [1,2,3], [4,5,6]] )

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3 4 5 6]]


### 分裂

分裂数组有两种方式:
1. 通用的split
2. 专门的hsplit,vsplit

In [40]:
arr=np.arange(25).reshape((5,5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


在 split() 函数里通过设定轴，来对数组沿着竖直方向分裂 (轴 0) 和沿着水平方向分裂 (轴 1)。 
split() 默认沿着轴 0 分裂，其第二个参数 [1, 3] 相当于是个切片操作，将数组分成三部分：

- :1 (即第 1 行)

- 1:3 (即第 2 到 3 行)

- 3:  (即第 4 到 5 行)

In [42]:
first, second, third = np.split(arr,[1,3])
print( 'The first split is', first )
print( 'The second split is', second )
print( 'The third split is', third )

The first split is [[0 1 2 3 4]]
The second split is [[ 5  6  7  8  9]
 [10 11 12 13 14]]
The third split is [[15 16 17 18 19]
 [20 21 22 23 24]]


vsplit() 和 split(axis=0) 等价，hsplit() 和 split(axis=1) 等价。

In [43]:
first, second, third = np.hsplit(arr,[1,3])
print( 'The first split is', first )
print( 'The second split is', second )
print( 'The third split is', third )

The first split is [[ 0]
 [ 5]
 [10]
 [15]
 [20]]
The second split is [[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]
The third split is [[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


## 重复和拼接

重复 (repeat) 和拼接 (tile) 这两个操作本质都是复制



- 重复是在元素层面复制

- 拼接是在数组层面复制

### 重复


函数 repeat() 复制的是数组的每一个元素，参数有几种设定方法：



- 一维数组：用标量和列表来复制元素的个数

- 多维数组：用标量和列表来复制元素的个数，用轴来控制复制的行和列

In [45]:
arr=np.arange(3)
print(arr)
print(arr.repeat(3))

[0 1 2]
[0 0 0 1 1 1 2 2 2]


In [46]:
print( arr.repeat([2,3,4]) )

[0 0 1 1 1 2 2 2 2]


In [47]:
arr2d = np.arange(6).reshape((2,3))
print( arr2d )
print( arr2d.repeat(2, axis=0) )

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]]


In [48]:
print( arr2d.repeat([2,3,4], axis=1) )

[[0 0 1 1 1 2 2 2 2]
 [3 3 4 4 4 5 5 5 5]]


### 拼接


函数 tile() 复制的是数组本身，参数有几种设定方法：



- 标量：把数组当成一个元素，一列一列复制

- 形状：把数组当成一个元素，按形状复制

In [50]:
arr2d=np.arange(6).reshape((2,3))
print(arr2d)
print(np.tile(arr2d,2))

[[0 1 2]
 [3 4 5]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]


In [51]:
print(np.tile(arr2d,(2,3)))

[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]


## 其他操作

### 排序

排序包括直接排序 (direct sort) 和间接排序 (indirect sort)。

#### 直接排序

In [53]:
arr=np.array([5,3,2,6,1,4])
print('Before sorting',arr)
arr.sort()
print('After sorting',arr)

Before sorting [5 3 2 6 1 4]
After sorting [1 2 3 4 5 6]


In [54]:
print(arr[::-1])

[6 5 4 3 2 1]


*知识点*

用来排序 numpy 用两种方式：

- arr.sort()

- np.sort( arr )


第一种 sort 会改变 arr，第二种 sort 在排序时创建了 arr 的一个复制品，不会改变 arr。

In [56]:
arr = np.random.randint( 40, size=(3,4) )
print( arr )

[[ 0 29 11  6]
 [25 13 37 21]
 [23 21 10  9]]


In [57]:
arr[:, 0].sort() 
print( arr )

[[ 0 29 11  6]
 [23 13 37 21]
 [25 21 10  9]]


In [58]:
np.sort(arr[:,1])

array([13, 21, 29])

In [59]:
print(arr)

[[ 0 29 11  6]
 [23 13 37 21]
 [25 21 10  9]]


此外也可以在不同的轴上排序，对于二维数组，在「轴 0」上排序是「跨行」排序，在「轴 1」上排序是「跨列」排序。

In [60]:
arr.sort(axis=1)
print( arr )

[[ 0  6 11 29]
 [13 21 23 37]
 [ 9 10 21 25]]


#### 间接排序

有时候我们不仅仅只想排序数组，还想在排序过程中提取每个元素在原数组对应的索引(index)，这时 argsort() 就派上用场了。以排列下面五个学生的数学分数为例：

In [61]:
score = np.array([100, 60, 99, 80, 91])
idx = score.argsort()
print( idx )

[1 3 4 2 0]


In [64]:
# 花式索引
print( score[idx] )

[ 60  80  91  99 100]


In [63]:
arr=np.random.randint(40,size=(3,4))
print(arr)

[[21 24  4 29]
 [20 38 21 31]
 [27  9  1  5]]


In [67]:
# 对二维数组做花式索引,对其第一行 arr[0] 排序，获取索引，在应用到所用行上。
arr[:, arr[0].argsort()]

array([[ 4, 21, 24, 29],
       [21, 20, 38, 31],
       [ 1, 27,  9,  5]])

### 插入和删除


和列表一样，我们可以给 numpy 数组



- 用insert()函数在某个特定位置之前插入元素

- 用delete()函数删除某些特定元素

In [73]:
a=np.arange(6)
print(a)
print(np.insert(a,1,100))
print(np.delete(a,[1,3]))

[0 1 2 3 4 5]
[  0 100   1   2   3   4   5]
[0 2 4 5]


### 复制

In [74]:
a = np.arange(6)
a_copy = a.copy()
print( 'Before changing value, a is', a )
print( 'Before changing value, a_copy is', a_copy )
a_copy[-1] = 99
print( 'After changing value, a_copy is', a_copy )
print( 'After changing value, a is', a )

Before changing value, a is [0 1 2 3 4 5]
Before changing value, a_copy is [0 1 2 3 4 5]
After changing value, a_copy is [ 0  1  2  3  4 99]
After changing value, a is [0 1 2 3 4 5]


# 数组的计算

数组的计算共有四大类:

    1.元素层面(element-wise)计算`
    2.线性代数(linsar algebra)计算
    3.元素整合(element aggregation)计算
    4.广播机制(broadcasting)计算

## 元素层面计算

Numpy 数组元素层面计算包括：



二元运算 (binary operation)：加减乘除

数学函数：倒数、平方、指数、对数

比较运算 (comparison)

In [76]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.ones((2,3)) * 2
print( arr1 )
print( arr2 )

[[1. 2. 3.]
 [4. 5. 6.]]
[[2. 2. 2.]
 [2. 2. 2.]]


In [81]:
print( arr1 + arr2 + 1 )
print( arr1 - arr2 )
print( arr1 * arr2 )
print( arr1 / arr2 )


print( 1 / arr1 )
print( arr1 ** 2 )
print( np.exp(arr1) ) #指数
print( np.log(arr1) ) #对数


print(arr1 > arr2)
print(arr1 > 3)

[[4. 5. 6.]
 [7. 8. 9.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[False False  True]
 [ True  True  True]]
[[False False False]
 [ True  True  True]]


## 线性代数层面计算

在机器学习、金融工程和量化投资的编程过程中，因为运行速度的要求，通常会向量化 (vectorization) 而涉及大量的线性代数运算，尤其是矩阵之间的乘积运算。



但是，在 NumPy 默认不采用矩阵运算，而是数组 (ndarray) 运算。矩阵只是二维，而数组可以是任何维度，因此数组运算更通用些。



如果你非要二维数组 arr2d 进项矩阵运算，那么可以通过调用以下函数来实现：



A = np.mat(arr2d)

A = np.asmatrix(arr2d)

In [82]:
arr2d = np.array([[1,2],[3,1]])
arr2d

array([[1, 2],
       [3, 1]])

In [83]:
A = np.asmatrix(arr2d)
A

matrix([[1, 2],
        [3, 1]])

In [85]:
# 转置
print( arr2d.T )
print( arr2d.transpose() )
print( A.T )

[[1 3]
 [2 1]]
[[1 3]
 [2 1]]
[[1 3]
 [2 1]]


In [86]:
# 求逆
print( np.linalg.inv(arr2d) )
print( A.I )
print( A**-1 )

[[-0.2  0.4]
 [ 0.6 -0.2]]
[[-0.2  0.4]
 [ 0.6 -0.2]]
[[-0.2  0.4]
 [ 0.6 -0.2]]


In [89]:
# 相乘
arr = np.array([1,2])
b = np.asmatrix(arr).T
print( arr.shape, b.shape )


print( arr2d*arr )
print( A*b )


print( arr2d*arr2d )
print( A*A )

#在数组上实现「矩阵相乘向量」和「矩阵相乘矩阵]
print( np.dot(arr2d,arr) )
print( np.dot(arr2d,arr2d) )

(2,) (2, 1)
[[1 4]
 [3 2]]
[[5]
 [5]]
[[1 4]
 [9 1]]
[[7 4]
 [6 7]]
[5 5]
[[7 4]
 [6 7]]


## 元素整合计算

在数组中，元素可以以不同方式整合 (aggregation)。拿求和 (sum) 函数来说，我们可以对数组



所有的元素求和

在某个轴 (axis) 上的元素求和

In [91]:
arr = np.arange(1,7).reshape((2,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
print( 'The total sum is', arr.sum() )
print( 'The sum across rows is', arr.sum(axis=0) )
print( 'The sum across columns is', arr.sum(axis=1) )

The total sum is 21
The sum across rows is [5 7 9]
The sum across columns is [ 6 15]


行和列这些概念对矩阵 (二维矩阵) 才适用，高维矩阵还是要用轴 (axis) 来区分每个维度。让我们抛弃「行列」这些特殊概念，拥抱「轴」这个通用概念来重看数组 (一到四维) 把。

规律：n 维数组就有 n 层方括号。最外层方括号代表「轴 0」即 axis=0，依次往里方括号对应的 axis 的计数加 1。



严格来说，numpy 打印出来的数组可以想象带有多层方括号的一行数字。比如二维矩阵可想象成



    [[1, 2, 3],[4, 5, 6]]



三维矩阵可想象成



    [[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]]



由于屏幕的宽度不够，我们才把它们写成一列列的，如下



    [ [ [1, 2, 3]

         [4, 5, 6] ] 

      [ [7, 8, 9] 

         [10, 11, 12] ] ]



但在你脑海里，应该把它们想成一整行。这样会便于你理解如何按不同轴做整合运算。

In [93]:
arr = np.arange(1,25).reshape((2,2,2,3))
print(arr)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]


In [94]:
print( 'The total sum is', arr.sum() )
print( 'The sum on axis0 is', arr.sum(axis=0) )
print( 'The sum on axis1 is', arr.sum(axis=1) )
print( 'The sum on axis2 is', arr.sum(axis=2) )
print( 'The sum on axis3 is', arr.sum(axis=3) )

The total sum is 300
The sum on axis0 is [[[14 16 18]
  [20 22 24]]

 [[26 28 30]
  [32 34 36]]]
The sum on axis1 is [[[ 8 10 12]
  [14 16 18]]

 [[32 34 36]
  [38 40 42]]]
The sum on axis2 is [[[ 5  7  9]
  [17 19 21]]

 [[29 31 33]
  [41 43 45]]]
The sum on axis3 is [[[ 6 15]
  [24 33]]

 [[42 51]
  [60 69]]]


## 广播机制计算

当对两个形状不同的数组按元素操作时，可能会触发「广播机制」。具体做法，先适当复制元素使得这两个数组形状相同后再按元素操作，两个步骤：



广播轴 (broadcast axis)：比对两个数组的维度，将形状小的数组的维度 (轴) 补齐

复制元素：顺着补齐的轴，将形状小的数组里的元素复制，使得最终形状和另一个数组吻合

In [95]:
# 元素 2 被广播到数组 arr 的所有元素上
arr = np.arange(5)
print( arr )
print( arr + 2 )

# 沿轴 0 的均值的一维数组被广播到数组 arr 的所有的行上
arr = np.arange(12).reshape((4,3))
print( arr )
print( arr.mean(axis=0) )
print( arr - arr.mean(axis=0) )

[0 1 2 3 4]
[2 3 4 5 6]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[4.5 5.5 6.5]
[[-4.5 -4.5 -4.5]
 [-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]
 [ 4.5  4.5  4.5]]


*知识点*

当我们对两个数组操作时，如果它们的形状



- 不相容 (incompatible)，广播机制不能进行

- 相容 (compatible)，广播机制可以进行



因此，进行广播机制分两步



检查两个数组形状是否兼容，即从两个形状元组最后一个元素，来检查



 a. 它们是否相等

 b. 是否有一个等于 1



一旦它们形状兼容，确定两个数组的最终形状。

In [96]:
a = np.array([[1,2,3]])
b = np.array([[4],[5],[6]])
print( 'The shape of a is', a.shape )
print( 'The shape of b is', b.shape )

The shape of a is (1, 3)
The shape of b is (3, 1)


回顾进行广播机制的两步



检查数组 a 和 b 形状是否兼容，从两个形状元组 (1, 3) 和 (3, 1)最后一个元素开始检查，发现它们都满足『有一个等于 1』的条件。



因此它们形状兼容，两个数组的最终形状为 (max(1,3), max(3,1)) = (3, 3)



到此，a 和 b 被扩展成 (3, 3) 的数组.

In [97]:
c = a + b
print( 'The shape of c is', c.shape )
print( 'a is', a )
print( 'b is', b )
print( 'c = a + b =', c )

The shape of c is (3, 3)
a is [[1 2 3]]
b is [[4]
 [5]
 [6]]
c = a + b = [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [98]:

a = np.array( [[[1,2,3], [4,5,6]]] )
b1 = np.array( [[1,1,1], [2,2,2], [3,3,3]] )
b2 = np.arange(3).reshape((1,3))
b3 = np.arange(6).reshape((2,3))
b4 = np.arange(12).reshape((2,2,3))
b5 = np.arange(6).reshape((2,1,3))
print( 'The dimension of a is', a.ndim, 'and the shape of a is', a.shape )
print( 'The dimension of b1 is', b.ndim, 'and the shape of b1 is', b1.shape, '\n')
print( 'The dimension of a is', a.ndim, 'and the shape of a is', a.shape )
print( 'The dimension of b2 is', b.ndim, 'and the shape of b2 is', b2.shape, '\n' )
print( 'The dimension of a is', a.ndim, 'and the shape of a is', a.shape )
print( 'The dimension of b3 is', b.ndim, 'and the shape of b3 is', b3.shape, '\n' )
print( 'The dimension of a is', a.ndim, 'and the shape of a is', a.shape )
print( 'The dimension of b4 is', b.ndim, 'and the shape of b4 is', b4.shape, '\n' )
print( 'The dimension of a is', a.ndim, 'and the shape of a is', a.shape )
print( 'The dimension of b5 is', b.ndim, 'and the shape of b5 is', b5.shape )

The dimension of a is 3 and the shape of a is (1, 2, 3)
The dimension of b1 is 2 and the shape of b1 is (3, 3) 

The dimension of a is 3 and the shape of a is (1, 2, 3)
The dimension of b2 is 2 and the shape of b2 is (1, 3) 

The dimension of a is 3 and the shape of a is (1, 2, 3)
The dimension of b3 is 2 and the shape of b3 is (2, 3) 

The dimension of a is 3 and the shape of a is (1, 2, 3)
The dimension of b4 is 2 and the shape of b4 is (2, 2, 3) 

The dimension of a is 3 and the shape of a is (1, 2, 3)
The dimension of b5 is 2 and the shape of b5 is (2, 1, 3)


对于数组 a 和 b1，它们形状是 (1, 2, 3) 和 (3, 3)。元组最后一个都是 3，兼容；倒数第二个是 3 和 2，即不相等，也没有一个是 1，不兼容！a 和 b1 不能进行广播机制。
a 和其他 b2, b3, b4, b5 都可以进行广播机制.
